import fs from 'node:fs'
import path from 'node:path'
import { getPlugins } from './plugins'

const typedGlobal = path.resolve(__dirname, '../src/typed-global.d.ts')
const typedGlobalOut = path.resolve(__dirname, '../dist/typed-global.d.ts')
const typedPluginsOut = path.resolve(__dirname, '../dist/typed-plugins.d.ts')

const imports: string[] = []

getPlugins().forEach((provider) => {
  imports.push(`import '${provider.path}'`)
})

const content = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by script. ‼️ DO NOT MODIFY THIS FILE ‼️
${imports.join('\n')}

export {}
`

fs.writeFileSync(typedPluginsOut, content, 'utf8')
fs.writeFileSync(typedGlobalOut, fs.readFileSync(typedGlobal, 'utf8'), 'utf8')
