import fs from 'node:fs'
import path from 'node:path'

export interface ImportedFile {
  dir: 'mixins' | 'plugins'
  name: string
  path: string
}

function readdirSync(root: string): string[] {
  return fs.readdirSync(root).flatMap((filename) => {
    if (filename.endsWith('.ts')) {
      return [filename]
    }
    else {
      return fs.readdirSync(path.resolve(root, filename)).map(v => `${filename}/${v}`)
    }
  })
}

export function getFiles(): ImportedFile[] {
  const mixins = readdirSync(path.resolve(__dirname, '../src/mixins'))
  const plugins = readdirSync(path.resolve(__dirname, '../src/plugins'))
  mixins.sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }))
  plugins.sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }))
  const files: ImportedFile[] = []
  for (const mixin of mixins) {
    const name = mixin.replace('.ts', '')
    if (name === 'index') {
      continue
    }
    files.push({
      dir: 'mixins',
      name: `_${name.replace(/\./g, '_').replace(/[-/]/g, '_')}`,
      path: `./${name}`,
    })
  }
  for (const plugin of plugins) {
    const name = plugin.replace('.ts', '')
    if (name === 'index') {
      continue
    }
    files.push({
      dir: 'plugins',
      name: `_${name.replace(/\./g, '_').replace(/[-/]/g, '_')}`,
      path: `./${name}`,
    })
  }
  return files
}

const dts = [
  { dir: 'mixins' },
  { dir: 'plugins' },
]
dts.forEach((item) => {
  const typedPluginsOut = path.resolve(__dirname, `../src/${item.dir}/index.ts`)
  const imports: string[] = []
  const entries: string[] = []
  getFiles().forEach((file) => {
    if (file.dir === item.dir) {
      const importPath = file.path
      const varName = file.name.replace(/[-\s]/g, '_')
      imports.push(`import ${varName} from '${importPath}'`)
      entries.push(`  ${varName},`)
    }
  })
  const content = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by script. ‼️ DO NOT MODIFY THIS FILE ‼️
${imports.join('\n')}

export const ${item.dir} = [
${entries.join('\n')}
]
`
  fs.writeFileSync(typedPluginsOut, content, 'utf8')
})
