/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by script. ‼️ DO NOT MODIFY THIS FILE ‼️
import _animate from './animate'
import _arrange from './arrange'
import _autoNest from './autoNest'
import _clipboard from './clipboard'
import _collaboration from './collaboration'
import _components from './components'
import _doc from './doc'
import _edit from './edit'
import _flexLayout from './flexLayout'
import _formatPaint from './formatPaint'
import _frame from './frame'
import _history from './history'
import _hover from './hover'
import _image from './image'
import _import from './import'
import _interactions from './interactions'
import _json from './json'
import _layers from './layers'
import _madeWith from './madeWith'
import _memory from './memory'
import _menu from './menu'
import _node from './node'
import _pen from './pen'
import _presence from './presence'
import _ruler from './ruler'
import _saveAs from './saveAs'
import _scroll from './scroll'
import _selection from './selection'
import _shape from './shape'
import _slice from './slice'
import _smartGuides from './smartGuides'
import _smartSelection from './smartSelection'
import _state from './state'
import _statusbar from './statusbar'
import _test from './test'
import _timeline from './timeline'
import _tool from './tool'
import _toolbelt from './toolbelt'
import _transform from './transform'
import _typography from './typography'
import _url from './url'
import _variables from './variables'
import _view from './view'
import _workflow from './workflow'
import _zoom from './zoom'

export const plugins = [
  _animate,
  _arrange,
  _autoNest,
  _clipboard,
  _collaboration,
  _components,
  _doc,
  _edit,
  _flexLayout,
  _formatPaint,
  _frame,
  _history,
  _hover,
  _image,
  _import,
  _interactions,
  _json,
  _layers,
  _madeWith,
  _memory,
  _menu,
  _node,
  _pen,
  _presence,
  _ruler,
  _saveAs,
  _scroll,
  _selection,
  _shape,
  _slice,
  _smartGuides,
  _smartSelection,
  _state,
  _statusbar,
  _test,
  _timeline,
  _tool,
  _toolbelt,
  _transform,
  _typography,
  _url,
  _variables,
  _view,
  _workflow,
  _zoom,
]
