/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by script. ‼️ DO NOT MODIFY THIS FILE ‼️
import _cancel from './cancel'
import _clipboard from './clipboard'
import _copyAs from './copyAs'
import _delete from './delete'
import _drawingTool from './drawingTool'
import _flip from './flip'
import _frame from './frame'
import _gif from './gif'
import _group from './group'
import _history from './history'
import _hover from './hover'
import _html from './html'
import _image from './image'
import _import from './import'
import _json from './json'
import _layerOrder from './layerOrder'
import _layerPosition from './layerPosition'
import _layers from './layers'
import _lock from './lock'
import _madeWith from './madeWith'
import _menu from './menu'
import _move from './move'
import _new from './new'
import _node from './node'
import _open from './open'
import _panels from './panels'
import _pen from './pen'
import _rotate from './rotate'
import _ruler from './ruler'
import _saveAs from './saveAs'
import _scroll from './scroll'
import _select from './select'
import _shape from './shape'
import _smartGuides from './smartGuides'
import _state from './state'
import _statusbar from './statusbar'
import _text from './text'
import _timeline from './timeline'
import _toolbelt from './toolbelt'
import _ui from './ui'
import _url from './url'
import _view from './view'
import _visibility from './visibility'
import _zoom from './zoom'

export const plugins = [
  _cancel,
  _clipboard,
  _copyAs,
  _delete,
  _drawingTool,
  _flip,
  _frame,
  _gif,
  _group,
  _history,
  _hover,
  _html,
  _image,
  _import,
  _json,
  _layerOrder,
  _layerPosition,
  _layers,
  _lock,
  _madeWith,
  _menu,
  _move,
  _new,
  _node,
  _open,
  _panels,
  _pen,
  _rotate,
  _ruler,
  _saveAs,
  _scroll,
  _select,
  _shape,
  _smartGuides,
  _state,
  _statusbar,
  _text,
  _timeline,
  _toolbelt,
  _ui,
  _url,
  _view,
  _visibility,
  _zoom,
]
