import fs from 'node:fs'
import path from 'node:path'
import { getProviders } from './providers'

const typedGlobal = path.resolve(__dirname, '../src/typed-global.d.ts')
const typedGlobalOut = path.resolve(__dirname, '../dist/typed-global.d.ts')
const typedProvidersOut = path.resolve(__dirname, '../dist/typed-providers.d.ts')

const imports: string[] = []

getProviders().forEach((provider) => {
  imports.push(`import '${provider.path}'`)
})

const content = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by typed-providers. ‼️ DO NOT MODIFY THIS FILE ‼️
${imports.join('\n')}

export {}
`

fs.writeFileSync(typedProvidersOut, content, 'utf8')
fs.writeFileSync(typedGlobalOut, fs.readFileSync(typedGlobal, 'utf8'), 'utf8')
