import fs from 'node:fs'
import path from 'node:path'

export interface ImportedProvider {
  name: string
  path: string
}

export function getProviders(): ImportedProvider[] {
  const providersDir = path.resolve(__dirname, '../src/providers')
  const files = fs
    .readdirSync(providersDir)
    .filter(fn => fn.endsWith('.ts') && !fn.endsWith('.d.ts'))
  files.sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }))
  const providers: ImportedProvider[] = []
  for (const file of files) {
    const name = path.basename(file, '.ts')
    providers.push({
      name: `_${name.replace(/\./g, '_').replace(/-/g, '_')}`,
      path: `./providers/${name}`,
    })
  }
  return providers
}

const typedProvidersOut = path.resolve(__dirname, '../src/preset-providers.ts')

const imports: string[] = []
const entries: string[] = []

getProviders().forEach((provider) => {
  const importPath = provider.path
  const varName = provider.name.replace(/[-\s]/g, '_')
  imports.push(`import ${varName} from '${importPath}'`)
  entries.push(`  ${varName},`)
})

const content = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by preset-providers. ‼️ DO NOT MODIFY THIS FILE ‼️
${imports.join('\n')}

export const presetProviders = [
${entries.join('\n')}
]
`

fs.writeFileSync(typedProvidersOut, content, 'utf8')
