/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by script. ‼️ DO NOT MODIFY THIS FILE ‼️
import _0_command from './plugins/0.command'
import _0_config from './plugins/0.config'
import _0_config_base from './plugins/0.config/base'
import _0_context from './plugins/0.context'
import _0_element from './plugins/0.element'
import _0_font from './plugins/0.font'
import _0_i18n from './plugins/0.i18n'
import _1_frame from './plugins/1.frame'
import _1_hotkey from './plugins/1.hotkey'
import _1_upload from './plugins/1.upload'
import _2_box from './plugins/2.box'
import _2_exporter from './plugins/2.exporter'
import _2_exporter_0_json from './plugins/2.exporter/0.json'
import _2_exporter_image from './plugins/2.exporter/image'
import _2_exporter_pdf from './plugins/2.exporter/pdf'
import _2_exporter_pptx from './plugins/2.exporter/pptx'
import _2_exporter_video from './plugins/2.exporter/video'
import _2_loader from './plugins/2.loader'
import _2_loader_image from './plugins/2.loader/image'
import _2_loader_json from './plugins/2.loader/json'
import _2_loader_pptx from './plugins/2.loader/pptx'
import _3_view from './plugins/3.view'
import _4_0_text from './plugins/4.0.text'
import _4_1_lock from './plugins/4.1.lock'
import _4_2_element from './plugins/4.2.element'
import _4_3_frame from './plugins/4.3.frame'
import _4_4_doc from './plugins/4.4.doc'
import _align from './plugins/align'
import _arrange from './plugins/arrange'
import _auxiliary from './plugins/auxiliary'
import _clipboard from './plugins/clipboard'
import _flip from './plugins/flip'
import _frame from './plugins/frame'
import _group from './plugins/group'
import _history from './plugins/history'
import _import from './plugins/import'
import _insert_element from './plugins/insert/element'
import _insert_image from './plugins/insert/image'
import _insert_text from './plugins/insert/text'
import _menu from './plugins/menu'
import _move from './plugins/move'
import _new from './plugins/new'
import _open from './plugins/open'
import _preference from './plugins/preference'
import _saveAs from './plugins/saveAs'
import _select from './plugins/select'
import _snapshot from './plugins/snapshot'
import _theme from './plugins/theme'
import _ui from './plugins/ui'
import _visibility from './plugins/visibility'
import _zoom from './plugins/zoom'

export const presetPlugins = [
  _0_command,
  _0_config,
  _0_config_base,
  _0_context,
  _0_element,
  _0_font,
  _0_i18n,
  _1_frame,
  _1_hotkey,
  _1_upload,
  _2_box,
  _2_exporter,
  _2_exporter_0_json,
  _2_exporter_image,
  _2_exporter_pdf,
  _2_exporter_pptx,
  _2_exporter_video,
  _2_loader,
  _2_loader_image,
  _2_loader_json,
  _2_loader_pptx,
  _3_view,
  _4_0_text,
  _4_1_lock,
  _4_2_element,
  _4_3_frame,
  _4_4_doc,
  _align,
  _arrange,
  _auxiliary,
  _clipboard,
  _flip,
  _frame,
  _group,
  _history,
  _import,
  _insert_element,
  _insert_image,
  _insert_text,
  _menu,
  _move,
  _new,
  _open,
  _preference,
  _saveAs,
  _select,
  _snapshot,
  _theme,
  _ui,
  _visibility,
  _zoom,
]
