/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by preset-providers. ‼️ DO NOT MODIFY THIS FILE ‼️
import _0_context from './providers/0.context'
import _0_element from './providers/0.element'
import _0_frame from './providers/0.frame'
import _0_i18n from './providers/0.i18n'
import _0_upload from './providers/0.upload'
import _1_0_config from './providers/1.0.config'
import _1_0_configBase from './providers/1.0.configBase'
import _1_1_command from './providers/1.1.command'
import _1_2_hotkey from './providers/1.2.hotkey'
import _2_0_box from './providers/2.0.box'
import _2_1_loader from './providers/2.1.loader'
import _2_2_exporter from './providers/2.2.exporter'
import _3_view from './providers/3.view'
import _4_0_text from './providers/4.0.text'
import _4_2_element from './providers/4.2.element'
import _4_2_elementLock from './providers/4.2.elementLock'
import _4_3_frame from './providers/4.3.frame'
import _4_4_doc from './providers/4.4.doc'
import _align from './providers/align'
import _arrange from './providers/arrange'
import _auxiliary from './providers/auxiliary'
import _clipboard from './providers/clipboard'
import _flip from './providers/flip'
import _font from './providers/font'
import _group from './providers/group'
import _history from './providers/history'
import _import from './providers/import'
import _insertImage from './providers/insertImage'
import _insertText from './providers/insertText'
import _menu from './providers/menu'
import _move from './providers/move'
import _new from './providers/new'
import _open from './providers/open'
import _preference from './providers/preference'
import _saveAs from './providers/saveAs'
import _select from './providers/select'
import _snapshot from './providers/snapshot'
import _theme from './providers/theme'
import _ui from './providers/ui'
import _visible from './providers/visible'
import _zoom from './providers/zoom'

export const presetProviders = [
  _0_context,
  _0_element,
  _0_frame,
  _0_i18n,
  _0_upload,
  _1_0_config,
  _1_0_configBase,
  _1_1_command,
  _1_2_hotkey,
  _2_0_box,
  _2_1_loader,
  _2_2_exporter,
  _3_view,
  _4_0_text,
  _4_2_element,
  _4_2_elementLock,
  _4_3_frame,
  _4_4_doc,
  _align,
  _arrange,
  _auxiliary,
  _clipboard,
  _flip,
  _font,
  _group,
  _history,
  _import,
  _insertImage,
  _insertText,
  _menu,
  _move,
  _new,
  _open,
  _preference,
  _saveAs,
  _select,
  _snapshot,
  _theme,
  _ui,
  _visible,
  _zoom,
]
