/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by script. ‼️ DO NOT MODIFY THIS FILE ‼️
import _0_context from './plugins/0.context'
import _0_element from './plugins/0.element'
import _0_font from './plugins/0.font'
import _0_frame from './plugins/0.frame'
import _0_i18n from './plugins/0.i18n'
import _0_upload from './plugins/0.upload'
import _1_0_config from './plugins/1.0.config'
import _1_0_configBase from './plugins/1.0.configBase'
import _1_1_command from './plugins/1.1.command'
import _1_2_hotkey from './plugins/1.2.hotkey'
import _2_0_box from './plugins/2.0.box'
import _2_1_loader from './plugins/2.1.loader'
import _2_2_exporter from './plugins/2.2.exporter'
import _3_view from './plugins/3.view'
import _4_0_text from './plugins/4.0.text'
import _4_2_element from './plugins/4.2.element'
import _4_2_elementLock from './plugins/4.2.elementLock'
import _4_3_frame from './plugins/4.3.frame'
import _4_4_doc from './plugins/4.4.doc'
import _align from './plugins/align'
import _arrange from './plugins/arrange'
import _auxiliary from './plugins/auxiliary'
import _clipboard from './plugins/clipboard'
import _flip from './plugins/flip'
import _frame from './plugins/frame'
import _group from './plugins/group'
import _history from './plugins/history'
import _import from './plugins/import'
import _insertImage from './plugins/insertImage'
import _insertText from './plugins/insertText'
import _lock from './plugins/lock'
import _menu from './plugins/menu'
import _move from './plugins/move'
import _new from './plugins/new'
import _open from './plugins/open'
import _preference from './plugins/preference'
import _saveAs from './plugins/saveAs'
import _select from './plugins/select'
import _snapshot from './plugins/snapshot'
import _theme from './plugins/theme'
import _ui from './plugins/ui'
import _visibility from './plugins/visibility'
import _zoom from './plugins/zoom'

export const presetPlugins = [
  _0_context,
  _0_element,
  _0_font,
  _0_frame,
  _0_i18n,
  _0_upload,
  _1_0_config,
  _1_0_configBase,
  _1_1_command,
  _1_2_hotkey,
  _2_0_box,
  _2_1_loader,
  _2_2_exporter,
  _3_view,
  _4_0_text,
  _4_2_element,
  _4_2_elementLock,
  _4_3_frame,
  _4_4_doc,
  _align,
  _arrange,
  _auxiliary,
  _clipboard,
  _flip,
  _frame,
  _group,
  _history,
  _import,
  _insertImage,
  _insertText,
  _lock,
  _menu,
  _move,
  _new,
  _open,
  _preference,
  _saveAs,
  _select,
  _snapshot,
  _theme,
  _ui,
  _visibility,
  _zoom,
]
