/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by script. ‼️ DO NOT MODIFY THIS FILE ‼️
import _0_command from './mixins/0.command'
import _0_config from './mixins/0.config'
import _0_config_base from './mixins/0.config/base'
import _0_context from './mixins/0.context'
import _0_font from './mixins/0.font'
import _0_helper from './mixins/0.helper'
import _0_locale from './mixins/0.locale'
import _1_frame from './mixins/1.frame'
import _1_hotkey from './mixins/1.hotkey'
import _1_screen from './mixins/1.screen'
import _1_timeline from './mixins/1.timeline'
import _1_upload from './mixins/1.upload'
import _2_box from './mixins/2.box'
import _2_export from './mixins/2.export'
import _2_load from './mixins/2.load'
import _3_view from './mixins/3.view'
import _4_0_text from './mixins/4.0.text'
import _4_2_element from './mixins/4.2.element'
import _4_3_frame from './mixins/4.3.frame'
import _4_4_doc from './mixins/4.4.doc'
import _scroll from './mixins/scroll'
import _snapshot from './mixins/snapshot'
import _zoom from './mixins/zoom'

export const mixins = [
  _0_command,
  _0_config,
  _0_config_base,
  _0_context,
  _0_font,
  _0_helper,
  _0_locale,
  _1_frame,
  _1_hotkey,
  _1_screen,
  _1_timeline,
  _1_upload,
  _2_box,
  _2_export,
  _2_load,
  _3_view,
  _4_0_text,
  _4_2_element,
  _4_3_frame,
  _4_4_doc,
  _scroll,
  _snapshot,
  _zoom,
]
