/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by script. ‼️ DO NOT MODIFY THIS FILE ‼️
import _0_command from './mixins/0.command'
import _0_config from './mixins/0.config'
import _0_config_base from './mixins/0.config/base'
import _0_context from './mixins/0.context'
import _0_element from './mixins/0.element'
import _0_font from './mixins/0.font'
import _0_i18n from './mixins/0.i18n'
import _1_frame from './mixins/1.frame'
import _1_hotkey from './mixins/1.hotkey'
import _1_timeline from './mixins/1.timeline'
import _1_upload from './mixins/1.upload'
import _2_box from './mixins/2.box'
import _2_exporter from './mixins/2.exporter'
import _2_exporter_json from './mixins/2.exporter/json'
import _2_loader from './mixins/2.loader'
import _2_loader_json from './mixins/2.loader/json'
import _3_view from './mixins/3.view'
import _4_0_text from './mixins/4.0.text'
import _4_1_lock from './mixins/4.1.lock'
import _4_2_element from './mixins/4.2.element'
import _4_3_frame from './mixins/4.3.frame'
import _4_4_doc from './mixins/4.4.doc'
import _snapshot from './mixins/snapshot'

export const mixins = [
  _0_command,
  _0_config,
  _0_config_base,
  _0_context,
  _0_element,
  _0_font,
  _0_i18n,
  _1_frame,
  _1_hotkey,
  _1_timeline,
  _1_upload,
  _2_box,
  _2_exporter,
  _2_exporter_json,
  _2_loader,
  _2_loader_json,
  _3_view,
  _4_0_text,
  _4_1_lock,
  _4_2_element,
  _4_3_frame,
  _4_4_doc,
  _snapshot,
]
