/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by script. ‼️ DO NOT MODIFY THIS FILE ‼️
import _align from './plugins/align'
import _arrange from './plugins/arrange'
import _auxiliary from './plugins/auxiliary'
import _clipboard from './plugins/clipboard'
import _flip from './plugins/flip'
import _frame from './plugins/frame'
import _group from './plugins/group'
import _history from './plugins/history'
import _image from './plugins/image'
import _import from './plugins/import'
import _menu from './plugins/menu'
import _move from './plugins/move'
import _new from './plugins/new'
import _open from './plugins/open'
import _preference from './plugins/preference'
import _saveAs from './plugins/saveAs'
import _select from './plugins/select'
import _text from './plugins/text'
import _ui from './plugins/ui'
import _visibility from './plugins/visibility'
import _zoom from './plugins/zoom'

export const plugins = [
  _align,
  _arrange,
  _auxiliary,
  _clipboard,
  _flip,
  _frame,
  _group,
  _history,
  _image,
  _import,
  _menu,
  _move,
  _new,
  _open,
  _preference,
  _saveAs,
  _select,
  _text,
  _ui,
  _visibility,
  _zoom,
]
