/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by script. ‼️ DO NOT MODIFY THIS FILE ‼️
import _auxiliary from './plugins/auxiliary'
import _clipboard from './plugins/clipboard'
import _copyAs from './plugins/copyAs'
import _delete from './plugins/delete'
import _flip from './plugins/flip'
import _frame from './plugins/frame'
import _gif from './plugins/gif'
import _group from './plugins/group'
import _history from './plugins/history'
import _html from './plugins/html'
import _image from './plugins/image'
import _import from './plugins/import'
import _json from './plugins/json'
import _layerOrder from './plugins/layerOrder'
import _layerPosition from './plugins/layerPosition'
import _lock from './plugins/lock'
import _menu from './plugins/menu'
import _move from './plugins/move'
import _new from './plugins/new'
import _open from './plugins/open'
import _saveAs from './plugins/saveAs'
import _select from './plugins/select'
import _text from './plugins/text'
import _ui from './plugins/ui'
import _url from './plugins/url'
import _view from './plugins/view'
import _visibility from './plugins/visibility'
import _zoom from './plugins/zoom'

export const plugins = [
  _auxiliary,
  _clipboard,
  _copyAs,
  _delete,
  _flip,
  _frame,
  _gif,
  _group,
  _history,
  _html,
  _image,
  _import,
  _json,
  _layerOrder,
  _layerPosition,
  _lock,
  _menu,
  _move,
  _new,
  _open,
  _saveAs,
  _select,
  _text,
  _ui,
  _url,
  _view,
  _visibility,
  _zoom,
]
