import { definePlugin } from 'mce'
import { ANIMATION_PRESETS } from './presets'

export function plugin() {
  return definePlugin((editor) => {
    ANIMATION_PRESETS.forEach(preset => editor.registerAnimationPreset(preset))

    return {
      name: 'mce:animation-presets',
      // 预设的显示名（菜单按 t(preset.id) 取），随包携带，不放核心。
      messages: {
        en: {
          // 进入
          fadeIn: 'Fade in',
          zoomIn: 'Zoom in',
          brakeIn: 'Brake in',
          rotateIn: 'Rotate in',
          rollIn: 'Roll in',
          bounceZoomIn: 'Bounce zoom in',
          bounceShrinkIn: 'Bounce shrink in',
          fadeInUp: 'Fade in up',
          fadeInDown: 'Fade in down',
          fadeInLeft: 'Fade in left',
          fadeInRight: 'Fade in right',
          flyInUp: 'Fly in up',
          flyInDown: 'Fly in down',
          flyInLeft: 'Fly in left',
          flyInRight: 'Fly in right',
          bounceInUp: 'Bounce in up',
          bounceInDown: 'Bounce in down',
          bounceInLeft: 'Bounce in left',
          bounceInRight: 'Bounce in right',
          unfoldUp: 'Unfold up',
          unfoldDown: 'Unfold down',
          unfoldLeft: 'Unfold left',
          unfoldRight: 'Unfold right',
          zoomInUp: 'Zoom in up',
          zoomInDown: 'Zoom in down',
          zoomInLeft: 'Zoom in left',
          zoomInRight: 'Zoom in right',
          rotateInTopLeft: 'Rotate in top-left',
          rotateInTopRight: 'Rotate in top-right',
          rotateInBottomLeft: 'Rotate in bottom-left',
          rotateInBottomRight: 'Rotate in bottom-right',
          // 强调
          bounce: 'Bounce',
          flash: 'Flash',
          pulse: 'Pulse',
          rubberBand: 'Rubber band',
          shake: 'Shake',
          wobble: 'Wobble',
          tada: 'Tada',
          swing: 'Swing',
          jelly: 'Jelly',
          spin: 'Spin',
          spinReverse: 'Spin reverse',
          panUp: 'Pan up',
          panDown: 'Pan down',
          panLeft: 'Pan left',
          panRight: 'Pan right',
          // 退出
          disappear: 'Disappear',
          fadeOut: 'Fade out',
          bounceOut: 'Bounce out',
          zoomOut: 'Zoom out',
          rotateOut: 'Rotate out',
          hinge: 'Hinge',
          lightSpeedOut: 'Light speed out',
          rollOut: 'Roll out',
          fadeOutUp: 'Fade out up',
          fadeOutDown: 'Fade out down',
          fadeOutLeft: 'Fade out left',
          fadeOutRight: 'Fade out right',
          flyOutUp: 'Fly out up',
          flyOutDown: 'Fly out down',
          flyOutLeft: 'Fly out left',
          flyOutRight: 'Fly out right',
          bounceOutUp: 'Bounce out up',
          bounceOutDown: 'Bounce out down',
          bounceOutLeft: 'Bounce out left',
          bounceOutRight: 'Bounce out right',
          rotateOutTopRight: 'Rotate out top-right',
          rotateOutTopLeft: 'Rotate out top-left',
          rotateOutBottomLeft: 'Rotate out bottom-left',
          rotateOutBottomRight: 'Rotate out bottom-right',
          zoomOutUp: 'Zoom out up',
          zoomOutDown: 'Zoom out down',
          zoomOutLeft: 'Zoom out left',
          zoomOutRight: 'Zoom out right',
        },
        zhHans: {
          // 进入
          fadeIn: '淡入',
          zoomIn: '放大',
          brakeIn: '刹车',
          rotateIn: '旋转',
          rollIn: '转入',
          bounceZoomIn: '弹性放大',
          bounceShrinkIn: '弹性缩小',
          fadeInUp: '向上淡入',
          fadeInDown: '向下淡入',
          fadeInLeft: '向左淡入',
          fadeInRight: '向右淡入',
          flyInUp: '向上飞入',
          flyInDown: '向下飞入',
          flyInLeft: '向左飞入',
          flyInRight: '向右飞入',
          bounceInUp: '向上弹跳',
          bounceInDown: '向下弹跳',
          bounceInLeft: '向左弹跳',
          bounceInRight: '向右弹跳',
          unfoldUp: '向上展开',
          unfoldDown: '向下展开',
          unfoldLeft: '向左展开',
          unfoldRight: '向右展开',
          zoomInUp: '向上放大',
          zoomInDown: '向下放大',
          zoomInLeft: '向左放大',
          zoomInRight: '向右放大',
          rotateInTopLeft: '左上旋入',
          rotateInTopRight: '右上旋入',
          rotateInBottomLeft: '左下旋入',
          rotateInBottomRight: '右下旋入',
          // 强调
          bounce: '弹跳',
          flash: '闪现',
          pulse: '脉冲',
          rubberBand: '橡皮筋',
          shake: '震动',
          wobble: '钟摆',
          tada: '嘀嗒',
          swing: '摇晃',
          jelly: '果冻',
          spin: '旋转',
          spinReverse: '反向旋转',
          panUp: '向上平移',
          panDown: '向下平移',
          panLeft: '向左平移',
          panRight: '向右平移',
          // 退出
          disappear: '消失',
          fadeOut: '淡出',
          bounceOut: '弹跳',
          zoomOut: '缩小',
          rotateOut: '旋转',
          hinge: '悬挂脱落',
          lightSpeedOut: '加速退出',
          rollOut: '转出',
          fadeOutUp: '向上淡出',
          fadeOutDown: '向下淡出',
          fadeOutLeft: '向左淡出',
          fadeOutRight: '向右淡出',
          flyOutUp: '向上飞出',
          flyOutDown: '向下飞出',
          flyOutLeft: '向左飞出',
          flyOutRight: '向右飞出',
          bounceOutUp: '向上弹跳',
          bounceOutDown: '向下弹跳',
          bounceOutLeft: '向左弹跳',
          bounceOutRight: '向右弹跳',
          rotateOutTopRight: '右上旋出',
          rotateOutTopLeft: '左上旋出',
          rotateOutBottomLeft: '左下旋出',
          rotateOutBottomRight: '右下旋出',
          zoomOutUp: '向上缩小',
          zoomOutDown: '向下缩小',
          zoomOutLeft: '向左缩小',
          zoomOutRight: '向右缩小',
        },
      },
    }
  })
}
